### ISSUE TITLE
Update pretty please (with cherry on top)

### ISSUE THREAD

**Issue by BertrandLF** [Ninja-Squad/poneyserver#8]
I would like to run the back-end server locally to complete the pony race course (our company blocks sockets). 

This version seems quite old compared to what the ponyracer app expects (different auth, pony model missing, ...). 

Could you please push the changes you have in prod to this repo?

Thanks!

**Comment by cexbrayat** [comment]
@BertrandLF This is not the right backend : it's the one we used for our training on AngularJS 1.x :)

We don't plan to release the version we use for the Pro Pack sorry. It would require too much work on our side (scrub the private keys, document how to set it up, with all the dependencies needed, etc...) and we rather prefer to keep our energy to add content to the ebook and new exercises to the Pro Pack (which take us most of our time). 

I hope you'll find an Internet connection with no limitation (we sometimes use our phones when we give trainings in companies like yours).
